api_platform:
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
    # Make order parameter name to be a global for every entity
    #collection:
    #    order_parameter_name: '_order'
